name: Cypress Front Tests

on:
  push:
  pull_request:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./testProject
        run: npm install

      - name: Install Angular CLI
        working-directory: ./testProject
        run: npm install @angular/cli@latest --save-dev

      - name: Start Angular frontend
        working-directory: ./testProject
        run: nohup ./node_modules/.bin/ng serve --port 4200 --host 0.0.0.0 &

      - name: Wait for frontend
        run: npx wait-on http://localhost:4200

      - name: Run Cypress tests
        working-directory: ./testProject
        run: npx cypress run
